### ISSUE TITLE
Bot leaves VC after left idle and won't re-join

### ISSUE THREAD

**Issue by Pigmess** [ArrowM/Queue-Bot#8]
See title. Perhaps this is more of a support case (I sent a friend request to the Discord name you mentioned in another issue, maybe better medium?) but here's what I've experienced:

The bot initially worked exactly as described to create a VC queue that pulls someone into another (private) VC when it's dragged in.

I left the queue bot in the queue VC overnight, returned to find it missing though the queue status remained and updates when I join the VC. Problem is, no bot in the VC means I can't drag it into the other VC to pull people off the queue.

Nothing in the top gg description seems to indicate a way to trigger the bot to rejoin the VC. I also tried deleting and remaking the queue but the bot still doesn't join the queue VC.

No changes have been made to permissions for these VCs in the meantime.

**Comment by Pigmess** [comment]
Note, I have tried the !start command using the VC name - but this does nothing currently. Happy to discuss / provide further detail as needed.

**Comment by Pigmess** [comment]
It looks like the bot is entirely offline/down now, so maybe this is related / a side effect rather than a bug.

**Comment by daltonmeck** [comment]
Hey, It looks like the bot was having issues earlier today (I think it was an issue with PM2, the process manager I use). The bot should be back and working now.
As you said, `!start` can be used to add the bot to a voice channel. I saw your friend request. I thought it was a spam request since we both are in the Deep Rock server, whoops. Please send the request again if the issue isn't resolved.

**Comment by Arrowman6677** [comment]
Hey, It looks like the bot was having issues earlier today (I think it was an issue with PM2, the process manager I use). The bot should be back and working now.
As you said, !start can be used to add the bot to a voice channel. I saw your friend request. I thought it was a spam request since we both are in the Deep Rock server, whoops. Please send the request again if the issue isn't resolved.

**Comment by Pigmess** [comment]
Not sure what the initial issue was (possibly just unfortunate timing with pm2 going down) but I seem to have side-stepped it by hosting on my laptop (I only ever plan to use it while I'm online anyhow). I'll send the Discord invite again - I have a few suggestions for additions to the bot hosting setup (though the instructions are overall quite good).
